export const Auth = {
  english: {
    signupHeading: "Signup Here",
    signupDesc:
      "Our company is on a mission to transform and revolutionize the farming industry through a seamless and technology-driven ecosystem.",
    signupTitle: "Create your account here",
    name: "Full Name",
    namePlaceholder: "Enter your full name",
    email: "Email",
    emailPlaceholder: "Enter you email id",
    mobile_number: "Mobile Number",
    mobile_numberPlaceholder: "Enter your mobile number",
    options: [
      { label: "Farmer", value: "Farmer" },
      { label: "Partner", value: "Partner" },
      { label: "Admin", value: "Admin" },
    ],
    type: "User Type",
    selectType: "Select Type",
    password: "Password",
    passwordPlaceholder: "Enter your password",
    conPassword: "Confirm Password",
    conPasswordPlaceholder: "Both password and confirm password should be same",
    signupBtn: "Sign Up",
    alreadyAc: "Already have account?",
    loginNowLink: "Login now",
    allRequiredMsg: "All details are required!",
    invalidEmailMsg: "Invalid email!",
    typeRequiredMsg: "User type is Required",
    invalidMobMsg: "Invalid mobile number!",
    invalidPassMsg: "Password and Confirm password doesn't match!",
    createdSuccessMsg: "Account Created Successfully!",
    somethingWrongMsg: "Something went wrong!",
    username: "Username",
    usernamePlaceholder: "Enter your email or mobile no.",
    loginPassword: "Password",
    loginPasswordPlaceholder: "Enter your password",
    loginHeading: "Login Now",
    loginDesc:
      "Welcome back to the farm! Please enter your credentials to access your account and explore our bountiful world of agriculture. We're excited to have you back as a part of our farming community.",
    loginTitle: "Enter your details",
    dontHave: "Don't have account?",
    forgot: "Forgotten Password?",
    loginBtn: "Log in",
    invalidUserMsg: "Invalid username or password!",
    loginSuccess: "Login Successfully!",
  },
  hindi: {
    signupHeading: "यहां साइन अप करें",
    signupDesc:
      "हमारी कंपनी एक निर्बाध और प्रौद्योगिकी-संचालित पारिस्थितिकी तंत्र के माध्यम से कृषि उद्योग को बदलने और क्रांति लाने के मिशन पर है",
    signupTitle: "यहां अपना अकाउंट बनाएं",
    name: "पूरा नाम",
    namePlaceholder: "अपना पूरा नाम लिखें",
    email: "ईमेल",
    emailPlaceholder: "अपना ईमेल आईडी लिखें",
    mobile_number: "मोबाईल नंबर",
    mobile_numberPlaceholder: "अपना मोबाइल नंबर लिखें",
    options: [
      { label: "किसान", value: "Farmer" },
      { label: "साथी", value: "Partner" },
      { label: "व्यवस्थापक", value: "Admin" },
    ],
    type: "उपयोगकर्ता का प्रकार",
    selectType: "चुनिए",
    password: "पासवर्ड",
    passwordPlaceholder: "अपना पासवर्ड लिखें",
    conPassword: "कन्फर्म पासवर्ड",
    conPasswordPlaceholder:
      "पासवर्ड और कन्फर्म पासवर्ड दोनों एक जैसे होने चाहिए",
    signupBtn: "साइन अप",
    alreadyAc: "पहले से ही अकाउंट है?",
    loginNowLink: "लॉगिन करें",
    allRequiredMsg: "सारी जानकारी आवश्यक है!",
    invalidEmailMsg: "ईमेल ग़लत है!",
    typeRequiredMsg: "उपयोगकर्ता प्रकार आवश्यक है!",
    invalidMobMsg: "मोबाइल नंबर गलत है!",
    invalidPassMsg: "पासवर्ड और कन्फर्म पासवर्ड एक जैसे होने चाहिए!",
    createdSuccessMsg: "अकाउंट सफलतापूर्वक बन गया!",
    somethingWrongMsg: "कुछ गलत हो गया!",
    username: "युजरनेम",
    usernamePlaceholder: "अपना ईमेल या मोबाइल नंबर लिखें.",
    loginPassword: "पासवर्ड",
    loginPasswordPlaceholder: "अपना पासवर्ड लिखें",
    loginHeading: "अभी लॉगिन करें",
    loginDesc:
      "खेती वेबसाइट के लॉगिन पेज पर आपका स्वागत है! कृषि के इस दुनिया में पहुंचने के लिए अपनी पहचान दर्ज करने के लिए कृपया अपना डिटेल दर्ज करें और हमारे खेती समुदाय का हिस्सा बनने के लिए तैयार रहें।",
    loginTitle: "अपनी जानकारी लिखें",
    dontHave: "अकाउंट नहीं है",
    forgot: "पासवर्ड याद नहीं है?",
    loginBtn: "लॉग इन करें",
    invalidUserMsg: "गलत उपयोगकर्ता नाम या पासवर्ड!",
    loginSuccess: "लॉगिन सफल",
  },
  marathi: {
    signupHeading: "येथे साइन अप करा",
    signupDesc:
      "आमची कंपनी अखंड आणि तंत्रज्ञान-चालित इकोसिस्टमद्वारे शेती उद्योगात परिवर्तन आणि क्रांती करण्याच्या मोहिमेवर आहे",
    signupTitle: "येथे तुमचे अकाउंट तयार करा",
    name: "पूर्ण नाव",
    namePlaceholder: "तुमचे पूर्ण नाव लिहा",
    email: "ईमेल",
    emailPlaceholder: "तुमचा ईमेल आयडी लिहा",
    mobile_number: "मोबाईल नंबर",
    mobile_numberPlaceholder: "तुमचा मोबाईल नंबर लिहा",
    options: [
      { label: "शेतकरी", value: "Farmer" },
      { label: "जोडीदार", value: "Partner" },
      { label: "प्रशासक", value: "Admin" },
    ],
    type: "वापरकर्ता प्रकार",
    selectType: "निवडा",
    password: "पासवर्ड",
    passwordPlaceholder: "तुमचा पासवर्ड लिहा",
    conPassword: "कन्फर्म पासवर्ड",
    conPasswordPlaceholder: "पासवर्ड आणि कन्फर्म पासवर्ड दोन्ही समान असावेत",
    signupBtn: "साइन अप",
    alreadyAc: "आधीच अकाउंट आहे?",
    loginNowLink: "लॉगिन करा",
    allRequiredMsg: "सर्व माहिती आवश्यक आहे!",
    invalidEmailMsg: "ईमेल चुकीचा आहे!",
    typeRequiredMsg: "वापरकर्ता प्रकार आवश्यक आहे!",
    invalidMobMsg: "मोबाईल नंबर चुकीचा आहे!",
    invalidPassMsg: "पासवर्ड आणि कन्फर्म पासवर्ड जुळले पाहिजेत!",
    createdSuccessMsg: "अकाउंट यशस्वीरित्या तयार झाले!",
    somethingWrongMsg: "काहीतरी चूक झाली!",
    username: "युजरनेम",
    usernamePlaceholder: "तुमचा ईमेल किंवा मोबाईल नंबर लिहा.",
    loginPassword: "पासवर्ड",
    loginPasswordPlaceholder: "तुमचा पासवर्ड लिहा",
    loginHeading: "आता लॉगिन करा",
    loginDesc:
      "शेती संकेतस्थळाच्या लॉगिन पॅजवर आपले स्वागत आहे! आपल्याच्या खेती समुदायाच्या भाग म्हणून आपला खाते डिटेल दर्ज करण्यात आपल्या सहाय्याच्या आवश्यकता आहे. आपल्याला पुन्हा आपल्या शेती समुदायात स्वागत आहे!",
    loginTitle: "तुमची माहिती लिहा",
    dontHave: "अकाउंट नाही",
    forgot: "पासवर्ड विसरलात?",
    loginBtn: "लॉग इन करा",
    invalidUserMsg: "चुकीचे वापरकर्तानाव किंवा पासवर्ड",
    loginSuccess: "लॉगिन यशस्वी",
  },
};
