export const Auth = {
    english: {
        signupHeading: "Signup Here",
        signupDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur temporibus nemo, aspernatur ipsa rem id assumenda doloremque sit dolores quo?',
        signupTitle: 'Create your account here',
        name:'Full Name',
        namePlaceholder:'Enter your full name',
        email: 'Email',
        emailPlaceholder: 'Enter you email id',
        phone: 'Mobile Number',
        phonePlaceholder: 'Enter your mobile number',
        password: 'Password',
        passwordPlaceholder:'Enter your password',
        conPassword: 'Confirm Password',
        conPasswordPlaceholder: 'Both password and confirm password should be same',
        signupBtn: 'Sign Up',
        alreadyAc: 'Already have account?',
        username: 'Username',
        usernamePlaceholder: 'Enter your email or mobile no.',
        loginPassword: 'Password',
        loginPasswordPlaceholder: 'Enter your password',
        loginHeading: 'Login Now',
        loginDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur temporibus nemo, aspernatur ipsa rem id assumenda doloremque sit dolores quo?',
        loginTitle: 'Enter your details',
        dontHave: "Don't have account?",
        forgot: 'Forgotten Password?',
        loginBtn: "Log in",
    },
    hindi: {
        signupHeading: 'यहां साइन अप करें',
        signupDesc: '',
        signupTitle: 'यहां अपना अकाउंट बनाएं',
        name:'पूरा नाम',
        namePlaceholder:'अपना पूरा नाम लिखें',
        email: "ईमेल",
        emailPlaceholder: 'अपना ईमेल आईडी लिखें',
        phone: 'मोबाईल नंबर',
        phonePlaceholder: 'अपना मोबाइल नंबर लिखें',
        password: 'पासवर्ड',
        passwordPlaceholder:'अपना पासवर्ड लिखें',
        conPassword: 'कन्फर्म पासवर्ड',
        conPasswordPlaceholder: 'पासवर्ड और कन्फर्म पासवर्ड दोनों एक जैसे होने चाहिए',
        signupBtn: 'साइन अप',
        alreadyAc: 'पहले से ही अकाउंट है?',
        username: 'युजरनेम',
        usernamePlaceholder: 'अपना ईमेल या मोबाइल नंबर लिखें.',
        loginPassword: 'पासवर्ड',
        loginPasswordPlaceholder: 'अपना पासवर्ड लिखें',
        loginHeading: 'अभी लॉगिन करें',
        loginDesc: '',
        loginTitle: 'अपनी जानकारी लिखें',
        dontHave: 'अकाउंट नहीं है',
        forgot: 'पासवर्ड याद नहीं है?',
        loginBtn: "लॉग इन करें",
       
    },
    marathi: {
        signupHeading: 'येथे साइन अप करा',
        signupDesc: '',
        signupTitle: 'येथे तुमचे अकाउंट तयार करा',
        name:'पूर्ण नाव',
        namePlaceholder:'तुमचे पूर्ण नाव लिहा',
        email:'ईमेल',
        emailPlaceholder: 'तुमचा ईमेल आयडी लिहा',
        phone: 'मोबाईल नंबर',
        phonePlaceholder: 'तुमचा मोबाईल नंबर लिहा',
        password: 'पासवर्ड',
        passwordPlaceholder:'तुमचा पासवर्ड लिहा',
        conPassword: 'कन्फर्म पासवर्ड',
        conPasswordPlaceholder: 'पासवर्ड आणि कन्फर्म पासवर्ड दोन्ही समान असावेत',
        signupBtn: 'साइन अप',
        alreadyAc: 'आधीच अकाउंट आहे?',
        username: 'युजरनेम',
        usernamePlaceholder: 'तुमचा ईमेल किंवा मोबाईल नंबर लिहा.',
        loginPassword: 'पासवर्ड',
        loginPasswordPlaceholder: 'तुमचा पासवर्ड लिहा',
        loginHeading: 'आता लॉगिन करा',
        loginDesc: '',
        loginTitle: 'तुमची माहिती लिहा',
        dontHave: 'अकाउंट नाही',
        forgot: 'पासवर्ड विसरलात?',
        loginBtn: "लॉग इन करा",
    },
}