

export const DealTableData = [
    {
        id: 1,
        name: 'John Doe',
        userId: 'johndoe',
        // // password: 'password123',
        role: 'Admin',
        department: 'HR',
        tvUser: 'Yes',
        status: true,
      },
      {
        id: 2,
        name: 'Jane Smith',
        userId: 'janesmith',
        // password: 'pass123',
        role: 'User',
        department: 'Finance',
        tvUser: 'No',
        status: false,
      },
      {
        id: 3,
        name: 'Alice Johnson',
        userId: 'alice',
        // password: 'alicerocks',
        role: 'Admin',
        department: 'IT',
        tvUser: 'Yes',
        status: true,
      },
      {
        id: 4,
        name: 'Bob Wilson',
        userId: 'bobwilson',
        // password: 'bob123',
        role: 'User',
        department: 'Sales',
        tvUser: 'Yes',
        status: true,
      },
      {
        id: 5,
        name: 'Eve Brown',
        userId: 'evebrown',
        // password: 'eve456',
        role: 'Admin',
        department: 'Marketing',
        tvUser: 'No',
        status: false,
      },
      {
        id: 6,
        name: 'David Lee',
        userId: 'davidlee',
        // password: 'davidpwd',
        role: 'User',
        department: 'Engineering',
        tvUser: 'Yes',
        status: true,
      },
      {
        id: 7,
        name: 'Sarah Johnson',
        userId: 'sarah',
        // password: 'sarahpass',
        role: 'Admin',
        department: 'HR',
        tvUser: 'No',
        status: false,
      },
      {
        id: 8,
        name: 'Michael Smith',
        userId: 'michaelsmith',
        // password: 'mike123',
        role: 'User',
        department: 'Finance',
        tvUser: 'Yes',
        status: true,
      },
      {
        id: 9,
        name: 'Emily Davis',
        userId: 'emilyd',
        // password: 'emily456',
        role: 'Admin',
        department: 'IT',
        tvUser: 'Yes',
        status: true,
      },
      {
        id: 10,
        name: 'Robert Wilson',
        userId: 'robertwilson',
        // password: 'rob123',
        role: 'User',
        department: 'Sales',
        tvUser: 'No',
        status: false,
      },
      {
        id: 11,
        name: 'Laura Brown',
        userId: 'laurabrown',
        // password: 'laura456',
        role: 'Admin',
        department: 'Marketing',
        tvUser: 'Yes',
        status: true,
      },
      {
        id: 12,
        name: 'Daniel Lee',
        userId: 'daniellee',
        // password: 'daniel123',
        role: 'User',
        department: 'Engineering',
        tvUser: 'No',
        status: false,
      },
      {
        id: 13,
        name: 'Olivia Smith',
        userId: 'oliviasmith',
        // password: 'olivia123',
        role: 'Admin',
        department: 'HR',
        tvUser: 'Yes',
        status: true,
      },
      {
        id: 14,
        name: 'James Johnson',
        userId: 'jamesjohnson',
        // password: 'james123',
        role: 'User',
        department: 'Finance',
        tvUser: 'Yes',
        status: true,
      },
      {
        id: 15,
        name: 'Sophia Davis',
        userId: 'sophiadavis',
        // password: 'sophia123',
        role: 'Admin',
        department: 'IT',
        tvUser: 'No',
        status: false,
      },
]