export const HomeData = {
  english: {
    loginBtn: "Login",
    signupBtn: "Sign Up",
    welcome: 'Welcome To',
    shetkariMitra: "Shetkari Mitra",
    info: "We help to connect farmer and agriculture equipment dealers",
    welcomeDesc: "To transform and revolutionize the farming industry by creating a seamless and technology-driven ecosystem, where farmers can easily access and schedule tractor services through our platform",
    knowMore: "Learn More",
    getStarted: 'Get Started',
  },
  hindi: {
    loginBtn: "लॉगिन",
    signupBtn: "साइन अप",
    welcome: 'आपका स्वागत है',
    shetkariMitra: "शेतकारी मित्र",
    info: 'हम किसान और कृषि उपकरण के मालिक को जोड़ने में मदद करते हैं',
    welcomeDesc: "एक अखंड आणि तंत्रज्ञान-चालित इकोसिस्टम तयार करून शेती उद्योगात परिवर्तन आणि क्रांती घडवून आणण्यासाठी, जिथे शेतकरी आमच्या प्लॅटफॉर्मद्वारे ट्रॅक्टर सेवा सहज मिळवू शकतात आणि शेड्यूल करू शकतात.",
    knowMore: "अधिक जानिए",
    getStarted: 'शुरू करें',
  },
  marathi: {
    loginBtn: "लॉगिन",
    signupBtn: "साइन अप",
    welcome: 'आपले स्वागत आहे',
    shetkariMitra: "शेतकारी मित्र",
    info: 'आम्ही शेतकरी आणि शेती उपकरणांचे मालक जोडण्यास मदत करतो',
    welcomeDesc: "एक निर्बाध और प्रौद्योगिकी-संचालित पारिस्थितिकी तंत्र बनाकर कृषि उद्योग को बदलने और क्रांति लाने के लिए, जहां किसान हमारे मंच के माध्यम से आसानी से ट्रैक्टर सेवाओं तक पहुंच और शेड्यूल कर सकते हैं।",
    knowMore: "अधिक जाणून घ्या",
    getStarted: 'सुरु करूया',
  },
};
